on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:    

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          dotnet-quality: preview
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Install native AOT prereqs
        run: sudo apt-get update && apt-get install -y --no-install-recommends clang zlib1g-dev
      - name: Publish
        run: dotnet publish -r linux-64 -c Release      
